export const CREATE_PAYMENT_ORDER = 'CREATE_PAYMENT_ORDER';
// export const PAYMENT_CALLBACK = 'PAYMENT_CALLBACK';
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING';
export const GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS';