export const CREATE_PAYMENT_ORDER = 'src/Payment/CREATE_PAYMENT_ORDER';
// export const PAYMENT_CALLBACK = 'src/Payment/PAYMENT_CALLBACK';
export const SET_PAYMENT_LOADING = 'src/Payment/SET_PAYMENT_LOADING';
export const GET_PAYMENT_STATUS = 'src/Payment/GET_PAYMENT_STATUS';
export const SET_RAZORPAY_PAYMENT_ORDER_ID = 'src/Payment/SET_RAZORPAY_PAYMENT_ORDER_ID';